### ISSUE TITLE
Improve web scraping data.

### ISSUE THREAD

**Issue by whoodes** [insightbulb/insightbulb#12]
The current web scraping only grabs the locations.  Next step is to grab the station numbers, and then finally tide data from the given station selection.

**Comment by escanut** [comment]
Can you post the URL.

**Comment by whoodes** [comment]
Hi @vicodescity, currently we are  planning on getting all data from: https://tidesandcurrents.noaa.gov/stations.html 

After selecting a region, we will then scrape the station number based off the region to get tide data from the url for that station.

**Comment by escanut** [comment]
Hi @Whoodes so from what I gathered you would want to scrape the station ID/number the the amount of feet and levels in the LST/LST section?

**Comment by escanut** [comment]
I would appreciate if you could send a copy of the script used to see if I could amend it to work for you and for you to check it out. I have actually doing webscraping for a few months now, so I think this will be another good opportunity to test my skills and learn.
Thanks.

**Comment by whoodes** [comment]
@vicodescity you can check ```tide_scraper.py``` in the root directory.  Although, this is a school project so I would have to inquire with my professor to see if we can accept contributions. Definitely feel free take a look and give me your thoughts on what we have (given it is a rough draft at this stage). I am closing this issue as we are getting all the data we need (aside from the actual tide data which will be opened in a separate issue), just perhaps not in the cleanest way.
