### ISSUE TITLE
Style main page

### ISSUE THREAD

**Issue by dkihe** [insightbulb/insightbulb#14]
Style the current main page.
- [x] Change background color to `#4EB0F6`
- [x] Change Font color to `#FFFFFF`
- [x] Decrease white space from buttons.  Buttons should still have some space between them.
- [x] Change font
- [x] Change font size when appropriate.
- [x] Style buttons.  Buttons should have a rounded border.  Border color should be the same as the selection bar `#0A8AE4` and the background color should be `#FFFFFF`.  On hover change background to `#0A8AE4`.

**Comment by whoodes** [comment]
Might want to hold off on the select bar styling, because I might have a way to send data to a bootstrap drop-down.

**Comment by dkihe** [comment]
I've edited the issue and got rid of the portion regarding the styling of the select bar.  Maybe it can be another issue for later once we figure it out.

**Comment by whoodes** [comment]
Completed.
