### ISSUE TITLE
Create a template for displaying tide information

### ISSUE THREAD

**Issue by dkihe** [insightbulb/insightbulb#15]
Using Jinja2, create a template that will display the following information:

- [x] Current Time
- [x] Current Date (Month/Day)
- [x] Location user is tracking
- [x] Current tide height
- [x] Time for the next tide
- [x] Indicate wether tide is high or low

The information should be set **below** the selection bar.

**Comment by dkihe** [comment]
Database is needed in oder to complete the following tasks:

- Current tide height
- Time for the next tide
- Indicate wether tide is high or low

**Comment by whoodes** [comment]
Implemented.
