### ISSUE TITLE
User Interface

### ISSUE THREAD

**Issue by christopherjnlau** [insightbulb/insightbulb#16]
- [ ] Maybe have a tutorial of some sort for new users (video, text boxes that pop up and can be disabled? etc.)
- [ ] Make data more eye pleasing
- [ ] Have multiple options when choosing region, view tides?
- [ ] Music option

**Comment by whoodes** [comment]
These seem more like additional features that can be considered after the core functionality is implemented.

**Comment by whoodes** [comment]
Closing as this probably won't happen.
